
server:
  port: 9091

spring:
  application:
    name: mate-service
  config:
    import : secret/application-secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    open-in-view: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



