spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/journeymate?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafy


cloud:
  aws:
    s3:
      bucket: journeymate-bucket
    credentials:
      access-key: AKIAQR4OSJQOHWEMDEVK
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false